import { factory, official } from '../factoryContent';
import { esc, reveal } from './html';

export function initClients(): void {
  const host=document.querySelector('#clients-content')!;
  if(!factory.clientGroups.length){host.innerHTML=`<p class="clients-notice" ${reveal('body')}>Объекты и партнёры ЧСГС</p><div class="client-tabs" ${reveal('ui',.12)} role="tablist" aria-label="Партнёры"><button role="tab" aria-selected="true" id="client-tab-source" aria-controls="client-panel-source">Объекты и партнёры</button><button role="tab" aria-selected="false" tabindex="-1" id="client-tab-network" aria-controls="client-panel-network">Дилерская сеть</button></div><div id="client-panel-source" class="client-panel" role="tabpanel" aria-labelledby="client-tab-source"><div class="client-placeholder-grid">${[1,2,3,4].map((i,index)=>`<div class="client-placeholder" ${reveal('card',.24+index*.12)}>Партнёр <span>0${i}</span><small>Логотип уточняется</small></div>`).join('')}</div><a class="text-link" ${reveal('ui',.36)} href="${official}/info_ld_plants/chsgs/">Объекты и партнёры на сайте ЛД ↗</a></div><div id="client-panel-network" class="client-panel" role="tabpanel" aria-labelledby="client-tab-network" hidden><p class="network-number">200+</p><p>Дилеров в России и за рубежом</p><a class="text-link" href="${official}/contacts/">Найти представителя ЛД ↗</a></div>`;}
  else {host.innerHTML=`<div class="client-tabs" ${reveal('ui',.12)} role="tablist" aria-label="Категории клиентов">${factory.clientGroups.map((g,i)=>`<button role="tab" id="client-tab-${g.id}" aria-controls="client-panel-${g.id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${esc(g.title)}</button>`).join('')}</div>${factory.clientGroups.map((g,i)=>`<div id="client-panel-${g.id}" class="client-panel" role="tabpanel" aria-labelledby="client-tab-${g.id}" ${i?'hidden':''}><div class="client-grid">${g.clients.map((c,index)=>`<div class="client-logo" ${reveal('card',.24+index*.12)}>${c.image?`<img src="${c.image}" width="240" height="100" loading="lazy" alt="${esc(c.name)}">`:`<span>${esc(c.name)}</span>`}</div>`).join('')}</div></div>`).join('')}`;}
  const tabs=Array.from(host.querySelectorAll<HTMLButtonElement>('[role="tab"]'));const activate=(i:number)=>tabs.forEach((tab,j)=>{tab.setAttribute('aria-selected',String(i===j));tab.tabIndex=i===j?0:-1;const panel=document.getElementById(tab.getAttribute('aria-controls')!)!;panel.hidden=i!==j;if(i===j){panel.querySelectorAll('.reveal').forEach(element=>element.classList.add('is-revealed'));panel.classList.remove('client-panel-enter');void panel.clientWidth;panel.classList.add('client-panel-enter');}});
  tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activate(i));tab.addEventListener('keydown',e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();activate(next);tabs[next]!.focus();});});
}
